# Generated by Django 3.2.7 on 2021-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211123_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, to='reviews.Tag'),
        ),
    ]
